// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package protoTiked is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Message
*/
package protoTiked

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Cmd              *string `protobuf:"bytes,1,req,name=cmd" json:"cmd,omitempty"`
	Target           *string `protobuf:"bytes,2,req,name=target,def=*" json:"target,omitempty"`
	Args             *string `protobuf:"bytes,3,opt,name=args" json:"args,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_Message_Target string = "*"

func (m *Message) GetCmd() string {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return ""
}

func (m *Message) GetTarget() string {
	if m != nil && m.Target != nil {
		return *m.Target
	}
	return Default_Message_Target
}

func (m *Message) GetArgs() string {
	if m != nil && m.Args != nil {
		return *m.Args
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "protoTiked.message")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x02, 0x53, 0x21, 0x99, 0xd9,
	0xa9, 0x29, 0x4a, 0x5e, 0x5c, 0xec, 0x50, 0x49, 0x21, 0x01, 0x2e, 0xe6, 0xe4, 0xdc, 0x14, 0x09,
	0x46, 0x05, 0x26, 0x0d, 0xce, 0x20, 0x10, 0x53, 0x48, 0x92, 0x8b, 0xad, 0x24, 0xb1, 0x28, 0x3d,
	0xb5, 0x44, 0x82, 0x09, 0x24, 0x68, 0xc5, 0xa8, 0x15, 0x04, 0x15, 0x10, 0x12, 0xe2, 0x62, 0x49,
	0x2c, 0x4a, 0x2f, 0x96, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x25, 0x97, 0xfb, 0x1b, 0x67, 0x00, 0x00, 0x00,
}
