; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24213.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\PC\AppData\Local\Temp\.NETFramework,Version=v4.5.2.AssemblyAttributes.cpp"
